### ISSUE TITLE
Changer URL http://*wikipedia.org en https://

### ISSUE THREAD

**Issue by Naereen** [LaurentClaessens/mazhe#120]
Je ne vais pas le faire avant d'avoir ton avis @LaurentClaessens, mais il pourrait être utile de changer toutes les adresses http:// en https:// si les sites en question sont en HTTPS par défaut.

Je pense notamment aux liens vers Wikipédia, en français ou en anglais, la plupart des liens sont en https:// mais j'ai quand même [trouvé 24 fichiers](https://github.com/LaurentClaessens/mazhe/search?q=%22http%3A%2F%2Ffr.wikipedia.org%22&unscoped_q=%22http%3A%2F%2Ffr.wikipedia.org%22) contenant `http://fr.wikipedia.org` et [8 fichiers](https://github.com/LaurentClaessens/mazhe/search?q=%22http%3A%2F%2Fen.wikipedia.org%22&unscoped_q=%22http%3A%2F%2Fen.wikipedia.org%22) contenant `http://en.wikipedia.org`.

**Comment by LaurentClaessens** [comment]
Le problème est que les pages de "citation" de Wikipédia semblent encore donner le code Bibtex avec http[^s]

[exemple](https://fr.wikipedia.org/w/index.php?title=Spécial:Citer&page=Léviathan&id=157294780)

Donc bon... tant que c'est pas fixé de ce côté ... c'est sûrement pas un mal de changer dans notre fichier bibtex, mais ce sera à refaire de temps en temps.

**Comment by Naereen** [comment]
Okay.
