### ISSUE TITLE
Problème \texttt{} pas utilisé dans \quext{} en introduction

### ISSUE THREAD

**Issue by Naereen** [LaurentClaessens/mazhe#121]
Dans la [note de bas de page 3 en introduction](https://laurent.claessens-donadello.eu/pdf/lefrido.pdf#Hfootnote.5) :
> "fonte \info{texttt}\quext{Comme celle-ci}"
https://github.com/LaurentClaessens/mazhe/blob/c1ff3590b99b5ca5b71902a423342591789d9f7d/tex/front_back_matter/remerciements.tex#L117

![morceau probleme intro Frido](https://user-images.githubusercontent.com/11994719/54983421-13b3d580-4fad-11e9-9afe-a027a44e4dea.png)

Je ne sais pas quel changement faire, je ne connais pas par coeur la macro pour faire une note de bas de page en `\texttt{...}` et pas en sans serif.

**Comment by LaurentClaessens** [comment]
J'ai un peu revu ce paragraphe. La commande que j'utilise est `\quext` parce qu'il s'agit de questions. La définition de cette macro est dans `e_mazhe.tex` et est:
```
\newcommand{\quext}[1]{\footnote{\textsf{#1}}}
```
Ce n'est pas très profond.

**Comment by Naereen** [comment]
Okay.
