### ISSUE TITLE
Manque 1 mot dans la proposition 13.110 

### ISSUE THREAD

**Issue by Provatiscus** [LaurentClaessens/mazhe#125]
J'imagine que c'est f-1 qui ne s'annule pas sur J

**Comment by LaurentClaessens** [comment]
Oui, il manque des mots. C'est f' qui ne s'annule pas sur I. La Wikiversité donne une preuve :
https://fr.wikiversity.org/wiki/Fonctions_d%27une_variable_réelle/Dérivabilité#Dérivée_et_opérations

**Comment by LaurentClaessens** [comment]
Au passage, je bouge cet énoncé parce qu'il est très proche de ce qui est en 13.118 juste en-dessous du titre "Dérivée de la réciproque"
