### ISSUE TITLE
Lemme 2.7 (sous-groupe engendré) faux ?

### ISSUE THREAD

**Issue by ColinPitrat** [LaurentClaessens/mazhe#140]
Le lemme 2.7 dit:
"Tout sous groupe de G contenant A est inclu dans gr(A)"

C'est incohérent avec la définition qui précède :
[gr(A)] est l'intersection de tous les sous-groupes de G contenant A.

Faut-il supprimer le lemme ? Ou le reformuler ?

**Comment by LaurentClaessens** [comment]
Le 28/09/2019 à 13:39, Colin Pitrat a écrit :
> Le lemme 2.7 dit:
> "Tout sous groupe de G contenant A est inclu dans gr(A)"
> 
> C'est incohérent avec la définition qui précède :
> [gr(A)] est l'intersection de tous les sous-groupes de G contenant A.
> 
> Faut-il supprimer le lemme ? Ou le reformuler ?


Effectivement. Ce n'est pas "est inclu dans" mais "contient".
Corrigé.
