### ISSUE TITLE
Ensembles équipotents : ajouter ou soustraire des cardinalités

### ISSUE THREAD

**Issue by cdrcprds** [LaurentClaessens/mazhe#146]
Le lemme 1.55 (qui dit que si deux sous-ensembles B et B'  sont équipotents, alors A\B et A\B' sont équipotents) ne fonctionne que pour des ensembles B et B' disjoints.

La dernière ligne de la démonstration tente de traiter le cas des ensembles non disjoints en se ramenant à deux parties disjointes C et C', mais ça ne fonctionne pas, car on n'a aucune garantie que les ensembles C et C' obtenus sont bien équipotents.

Un contre-exemple : Z\N et Z\Z ne sont pas équipotents.

Du coup, il faudra sans doute revoir la démonstration du lemme 1.61 (qui s'appuie en partie sur ce résultat).

**Comment by cdrcprds** [comment]
Par ailleurs, une note en bas de page dans la démonstration de la proposition 1.58 (qui établit une bijection entre un ensemble infini **S** et l'ensemble **{0;1}xS**) pose la question de l'utilisation de l'axiome du choix à un point donné de la démonstration.
Il s'agit de construire une fonction **phi : x -> phi_i(x)** en "choisissant" un indice **i€I** tel que **x€X_i**.

Bien que l'indice **i€I** ne soit pas nécessairement unique pour un x donné, la valeur **phi_i(x)** est en revanche bien unique (la discussion située juste au-dessus de la définition de phi le prouve).

On peut donc définir **phi(x)** comme étant l'unique élément de l'ensemble (indexé par i) : **{phi_i(x)}**.
Par conséquent, on n'a pas besoin de l'axiome du choix à cet endroit précis (bien sûr, dans la suite de la démonstration, qui utilise le lemme de Zorn, c'est une autre histoire).

**Comment by LaurentClaessens** [comment]
Bien vu. À première vue, il faut ajouter l'hypothèse que A est 
strictement surpotent à B et à B'.
Mais alors il faut être sûr que c'est suffisant pour les endroits où 
c'est utilisé.
Je verrai ça à tête reposée ...

PS : pour citer des résultats, au lieu de donner les numéros (p.ex 
1.55), on peut donner les labels qui sont affichée. Dans notre cas, 
c'est le "LEMooDHWSooFqhano".
C'est un peu moche, mais ça a l'avantage de ne pas bouger avec le temps, 
alors que les numéros peuvent facilement changer, parfois de beaucoup.

**Comment by LaurentClaessens** [comment]
Bon, j'ai ajouté l'hypothèse que B et B' sont disjoints.
D'autre part, j'ai adapté la démonstration du lemme "LEMooIVCBooHWQiZB". Maintenant elle n'utilise plus le premier.

Ça devrait être bon.

**Comment by LaurentClaessens** [comment]
J'ai précisé la définition de **phi**, et corrigé au passage une faute : j'avais oublié partout la dépendance de **phi** et **phi_i** en **k \in {0,1}**.

**Comment by cdrcprds** [comment]
- Pour **LEMooDHWSooFqhano** (**A\B** équipotent à **A\B'**) : c'est Ok.
- Pour **PropVCSooMzmIX** (**{0,1}xS** équipotent à **S**) : il reste quelques imprécisions.
	- Si **Y** est équipotent à **S** : on construit une fonction **f** qui est une _injection_ (et pas nécessairement une bijection) puisque **phi** n'est "qu'une" injection. C'est quand même suffisant parce que Cantor-Bernstein.
	- Si **Y** n'est pas équipotent à **S** : on justifie l'existence d'une bijection **g : {0,1}xN -> N**, en citant **LEMooUFCAooSyZtZj** (**A U B** équipotent à **A**) alors qu'il faudrait plutôt citer **LEMooRXSRooBUWOyb**.
Le reste de la démonstration est Ok.
- Pour **LEMooIVCBooHWQiZB** (**A\B** équipotent à **A**) : la démonstration n'est pas encore correcte :
Dans **SUBEQooTUWMooHIBLmJ** on justifie que "**A\B1** est surpotent à **B2**" alors qu'on a en fait besoin de "**A1\B1** est surpotent à **B2**".

**Comment by cdrcprds** [comment]
Une autre façon de procéder pour **LEMooIVCBooHWQiZB** :
On utilise **LEMooXMVDooIWLWis** (**A U B** équipotent à **A**) ainsi que le [théorème de comparabilité cardinale](https://fr.wikipedia.org/wiki/Th%C3%A9or%C3%A8me_de_comparabilit%C3%A9_cardinale) (qui utilise l'axiome du choix, mais il est de toutes façons déjà omniprésent dans ces histoires de cardinaux).

On écrit : **A = (A\B) U B**.
Le théorème de comparabilité cardinale nous garantit que l'un des deux cas suivants est vérifié :
- Si **A\B** est surpotent à **B** : la réunion des deux est alors équipotente à **A\B** (exactement ce qu'on voulait démontrer).
- Si **B** est surpotent à **A\B** : la réunion des deux est alors équipotente à **B** ; on a dans ce cas **A** et **B** équipotents (faux par hypothèse).

Reste encore à démontrer le théorème de comparabilité cardinale : [Wikipédia](https://fr.wikipedia.org/wiki/Th%C3%A9or%C3%A8me_de_comparabilit%C3%A9_cardinale) ne donne pas la démonstration complète, mais indique tout de même les grandes lignes :
- Montrer que l'ensemble des graphes d'injections d'une partie de A dans une partie de B est inductif.
- Il existe donc (lemme de Zorn) un élément maximal (au sens de l'inclusion), qui donne le graphe d'une injection de A dans B ou de B dans A.

**Comment by cdrcprds** [comment]
Encore une deernière chose : la démonstration de **PROPooFKBEooKXqujV** (**AxN** équipotent à **A**) est incomplète.
On construit des parties **A_i** et **B_i** qui vérifient un certain nombre de conditions... et la démonstration s'arrête là, sans conclusion.

**Comment by LaurentClaessens** [comment]
>     * Pour **LEMooIVCBooHWQiZB** (**A\B** équipotent à **A**) : la démonstration n'est pas encore correcte :
>       Dans **SUBEQooTUWMooHIBLmJ** on justifie que "**A\B1** est surpotent à **B2**" alors qu'on a en fait besoin de "**A1\B1** est surpotent à **B2**".

Nous avons l'injection
**(phi_1)^(-1): A\B_1  -> A\B** qui dit que **A\B >= A\B_1**.

Je laisse une note dans ce sens, mais je n'ose plus affirmer :)

**Comment by cdrcprds** [comment]
Malheureusement, je crois que ça ne marche pas :
**phi_1** transforme "bijectivement" **A\B** en **A_1\B_1**, donc **phi_1^(-1)** transforme **A_1\B_1** (et non **A\B_1**) en **A\B**.
La réciproque de **phi_1** n'est définie que sur **A_1**, pas sur **A** tout entier.

Je crois bien qu'il va falloir passer par le théorème de comparabilité cardinale.
Sur la page https://fr.wikipedia.org/wiki/Nombre_cardinal#Propri%C3%A9t%C3%A9s wikipédia présente le résultat à démontrer comme une conséquence de **LEMooXMVDooIWLWis** ; ils ne citent pas explicitement le théorème de comparabilité cardinale,  mais ils ont l'air de l'utiliser implicitement (cf la démonstration que j'ai écrite plus haut).

La démonstration du théorème de comparabilité cardinale n'est en fait pas si compliquée ; wikipédia en dessine une esquisse ici : https://fr.wikipedia.org/wiki/Lemme_de_Zorn#Ensemble_inductif (ils la prennent comme exemple d'utilisation du lemme de Zorn)

**Comment by cdrcprds** [comment]
Pour la preuve de **PROPooFKBEooKXqujV** :

- Dans la construction, pour A_0 et B_0 : il est dit deux fois qu'ils sont disjoints.
- Pour montrer que A_i et A_j sont disjoints, la chaîne d'inclusions serait plutôt : A_j < B_(j-1) < B_(j-**2**) < ... < B_i
(B_(j-1) apparaît deux fois)
- Dans la conclusion, je trouve le terme "inéquipotence" assez trompeur ; j'emploierais plutôt "la surpotence AxN >= A ".

Le reste me semble Ok.

**Comment by LaurentClaessens** [comment]
Effectivement, quand un truc est équivalent à l'axiome du choix, il ne faut pas insister : on ne trouvera pas d'astuces pour s'en passer.
Bref, c'est prouvé comme tu le disais, avec la comparabilité cardinale.

Merci pour la relecture.

**Comment by cdrcprds** [comment]
Pour **PROPooFKBEooKXqujV** :
La précision "A_i et B_i sont disjoints" a disparu : il fallait la laisser.
Quand j'avais parlé d'un doublon, je parlais de la phrase "Nous commençons à zéro en utilisant le corollaire 1.60 pour construire A0 et B0 dans A **disjoints** tels que A0 ~ B0 ~ A et tels que A0 et B0 sont **disjoints**."

Quelques remarques pour **THOooCBSKooCmzfUf** (théorème de comparabilité cardinale) :
- "Nous passons rapidement sur le fait que cet ensemble est inductif, et nous considérons tout de suite un élément maximal".
D'accord, mais il faudrait au moins faire référence au lemme de Zorn pour justifier l'existence de cet élément maximal.
- À propos de l'application **sigma** : "Elle n’est pas surjective si Y est différent de A".
Il faut plutôt écrire "Y différent de **B**".
- La distinction des cas à la fin (selon que Y=B ou non) n'est pas tout-à-fait bonne : même si Y=B, on ne sait pas si **phi : X->B** est surjective (on sait seulement que phi est une injection de X dans Y).
À la place, il faut distinguer les cas "**phi(X)=B**" (auquel cas, on a évidemment Y=B) et "**phi(X) différent de B**" (auquel cas, on dispose d'un **b€B\phi(X)** et on peut continuer la démonstration).

Pour **LEMooIVCBooHWQiZB**, c'est enfin bon (victoire !).

**Comment by LaurentClaessens** [comment]
En ce qui concerne la distinction **Y=B** ou non, en réalité, on peut toujours dire que **Y=B** parce qu'agrandir l'espace d'arrivé ne change rien à l'injectivité. Et d'ailleurs un élément maximal aura, pour cette raison, toujours **Y=B**.

À mon avis, il faut dire directement que l'ensemble est le triples **(X,Y,phi)** où **phi** est bijective. Ensuite, il faut montrer qu' un élément maximal aura soit **X=A** soit **Y=B**.

**Comment by cdrcprds** [comment]
Il reste une coquille dans la démonstration de la comparabilité cardinale :
Il est écrit vers la fin de la démonstration : "Nous sommes dans le cas X \neq A et **Y \neq B**".
Ce serait plutôt **phi(X) \neq B** (et non **Y**).

En dehors de ça, je pense que c'est bon.

**Comment by LaurentClaessens** [comment]
Si c'est bon, je ferme.
Il est temps de mettre ça en musique pour démontrer l'existence et l'unicité d'une clôture algébrique pour tout corps...
