### ISSUE TITLE
sin(0) should be equal to 0

### ISSUE THREAD

**Issue by iksnalybok** [LaurentClaessens/mazhe#153]
Juste après "_Par substitution directe dans les séries, nous avons immédiatement_", dans `175_trigono.tex` ligne 58.

**Comment by LaurentClaessens** [comment]
Corrigé. Merci.

Ceci n'a rien à voir avec cela, mais en voyant ton profil, ça me rappelle que tu as raison : il faudrait que je me bouge vers ... gitlab ?

**Comment by iksnalybok** [comment]
Je n'ai pas vraiment de recommendation. Gitlab une option viable. Je l'utilise, mais pas de manière intensive. J'ai eu de bons echos de sa fonctionalité de CI/CD (avec java). Le pricing a changé en ce début d'année (cf https://about.gitlab.com/blog/2021/01/26/new-gitlab-product-subscription-model/), mais un free plan est toujours disponible. Les projets qui recherchent de la visibilité s'affichent généralement sur github.
