### ISSUE TITLE
Certaines figures sont tronquées trop près de la bordure

### ISSUE THREAD

**Issue by quark67** [LaurentClaessens/mazhe#156]
Par exemple sur la figure 12.1 (code : https://github.com/LaurentClaessens/mazhe/blob/master/auto/pictures_tex/Fig_TangenteQuestion.pstricks), la partie extérieure des flèches des axes est tronqué, ce qui produit une demi-pointe :

![image](https://user-images.githubusercontent.com/9338576/134842100-c8c767db-e8aa-4882-8753-30583d3fc92b.png)

On voit également cela sur l'axe des abscisses des figures 12.3 (a)-(d).

**Comment by LaurentClaessens** [comment]
Corrigé en allongeant un peu les axes vers les négatifs.
