### ISSUE TITLE
question (2) et (7) de probabilités (section 1.4.3)

### ISSUE THREAD

**Issue by boutil** [LaurentClaessens/mazhe#16]
Bonjour,

Voici la réponse à la question 2 page 65 : oui
On a en effet $P(A|X)=E(1_A|X)$. Donc en utilisant le fait que l'espérance de l'espérance conditionnelle est l'espérance, on a : $E(P(A|X))=E(E(1_A|X))=E(1_A)=P(A)$.

Pour la question 7, la réponse est non. On imagine l'expérience suivante, où X et Y sont deux piles/faces équilibrés indépendants (représentés par 0,1). Et $\mathcal{A}$ est la tribu engendrée par l'événement A={(1,0),(1,0)}="les résultats des 2 lancers sont différents".
X et $\mathcal{A}$ sont independants, donc E(X|\mathcal{A})=E(X)=1/2. Pareil pour Y.
En revanche, le produit XY est nul sur A donc E(XY|\mathcal{A}) aussi. Ca ne peut donc etre égal à la constante 1/4=(1/2)^2.
C'est le même genre de chose qui dit que même si A et  B sont indépendants, alors P(A\cap B|C) n'est pas forcément le produit des probabilités conditionnelles.

**Comment by boutil** [comment]
Je mets aussi la réponse pour la question 3. Quand on passe au complémentaire dans l'équation 27,223b, on devrait avoir une inégalité large $1-P(X_n \geq a-\eta)$ pour conserver l'égalité. Mettre une inégalité stricte correspond à diminuer  la probabilité, et donc donner un majorant pour le membre de gauche.

**Comment by LaurentClaessens** [comment]
Merci. Vu que j'ai obtenu beaucoup de réponses à beaucoup de question, ça va prendre du temps à digérer, mais j'en tiendrai compte.

**Comment by LaurentClaessens** [comment]
Ok. C'est tenu compte. J'ai mis le temps ...
