### ISSUE TITLE
Casse des noms de fichiers

### ISSUE THREAD

**Issue by vkubicki** [LaurentClaessens/mazhe#161]
Bonjour,

sous macOS, il y a une collision de fichiers durant le clonage avec Git:

warning: les chemins suivants sont en collision (par exemple par des chemins
sensibles à la casse dans une système de fichier insensible) et un
seul du groupe en collision est dans l'arbre de travail :

  'auto/pictures_tex/Fig_SenoTopologo.pstricks'
  'auto/pictures_tex/Fig_senotopologo.pstricks'
  'src_yanntricks/Fig_SenoTopologo.pstricks.recall'
  'src_yanntricks/Fig_senotopologo.pstricks.recall'
  'src_yanntricks/yanntricksSenoTopologo.py'
  'src_yanntricks/yanntrickssenotopologo.py'

La compilation avec pdflatex fonctionne. Je ne maîtrise pas assez le projet pour définir l'action à réaliser, mais je suppose que la colision est liée à des reliquats qui ne sont plus utilisés, mais qui n'ont pas été détécté sous les OS qui n'ont pas de problème de casse.

**Comment by vkubicki** [comment]
Ouvert trop longtemps, pas d'activité.

**Comment by quark67** [comment]
Les fichiers avec le nom en camel case ("SenoTopologo") ne sont plus présents dans le projet actuellement. 

La suppression a eu lieu dès le 25 septembre 2022, soit le jour-même où vous avez signalé le problème : https://github.com/LaurentClaessens/mazhe/commit/a8c3311b3307e365e0c306de46ed730c61e78fac.
