### ISSUE TITLE
Le Frido, volume 1 - Plus disponible sur TheBookEdition !

### ISSUE THREAD

**Issue by Naereen** [LaurentClaessens/mazhe#17]
[Le volume 1](http://www.thebookedition.com/fr/le-frido-volume-1-p-344540.html) n'est *déjà* plus disponible ?

Bravo pour le succès si c'est dû à une grosse vente !
Est-ce que ça va se corriger tout seul (en attendant une ré-impression) ?

Je voulais lancer une demande d'achat auprès de la [BU de l'ENS Cachan](https://catalogue.ens-cachan.fr/).

**Comment by LaurentClaessens** [comment]
C'est une erreur de manipulation de ma part. Le fait est que 
thebookedition propose de vendre des epub; c'est la première question 
qui est posée lorsqu'on crée un nouveau livre. J'avais répondu "non" 
pour l'epub parce que je ne pensais pas que quelqu'un voudrais payer 
pour un version numérique alors que le pdf est en ligne.

Donc quand on m'a [parlé de faire un 
epub](https://github.com/LaurentClaessens/mazhe/issues/13#issuecomment-250718786), 
j'ai été modifier les paramètres du livre pour créer également un epub.

Bref, le texte est reparti en modération, et je n'ai même pas pu activer 
l'epub. Il sera de retour entre 24 et 78 heures. Et comme c'était jeudi 
soir, on risque d'attendre jusqu'à lundi ou mardi :(

Et le tout pour rien parce qu'on est d'accord que pdf->epub ne va pas aller.

**Comment by Naereen** [comment]
Ce n'est pas grave, rien n'est urgent dans cette affaire :smiley:.

**Comment by LaurentClaessens** [comment]
C'est à nouveau bon, à la même adresse qu'avant :
http://www.thebookedition.com/fr/le-frido-volume-1-p-344540.html
Si Cachan en veut, qu'elle n'hésite pas :)

**Comment by Naereen** [comment]
Super, merci.

J'attends la réponse de la BU de l'ENS Cachan (qui sera sûrement positive), mais la BU de l'ENS Rennes m'a déjà dit oui. :+1:
Je contacterai celle de l'ENS de Lyon dans la foulée.

L'objectif étant que cette version imprimée du Frido soit *vraiment* dans la malle d'agrég en juin prochain, en plusieurs exemplaires si possible.
