### ISSUE TITLE
+\ldots+  Vs +\cdots +

### ISSUE THREAD

**Issue by LaurentClaessens** [LaurentClaessens/mazhe#20]
mytskine [propose ici](https://github.com/LaurentClaessens/mazhe/pull/19#issue-180527868) une branche dont j'ai déjà pris tous les commit sauf un.

**EDIT** : ok, je me suis planté, j'ai pris ce commit aussi; j'ai été trop vite en fusionnant ma branche de test. Il n'empêche que la question reste.

QUESTION : lorsqu'on écrit une somme abrégée par trois points, vous préférez
a_1 + \ldots + a_n
ou bien
a_1 + \cdots + a_n

Personnellement je préfère ldots parce que ça fait plus aéré et parce que dans le cas d'un produit noté avec \cdot je vois mal
a_1\cdot \cdots \cdot a_n
(j'écris ça ici, mais je ne suis pas sûr d'avoir suivit cet avis dans mon propre texte)

**Comment by Naereen** [comment]
Je suis plus pour `\ldots` toujours.

**Comment by Naereen** [comment]
Et ce ne sera pas trop dur à vérifier, en `grep`ant les `\cdots` dans tous les `.tex`, non ?

**Comment by LaurentClaessens** [comment]
Non non, ce ne serait pas trop dur à changer. C'est pour ça qu'en voyant que j'avais quand même pris le commit "ldots->cdots", je ne me suis pas embarqué dans des acrobaties gitiennes pour l'enlever.
Si un consensus se dégage, il sera temps de faire des changements automatiques.

**Comment by boutil** [comment]
Je préfère personnellement \ldots pour les points de suspension dans une liste où on omet des termes entre des virgules par exemple. Mais pour une somme, je trouve que \cdots est plus adapté car il a le bon alignement vertical.

Le paquet amsmath propose d'utiliser des commandes sémantiques différentes suivant le contexte \dotsc, \dotsb, \dotsm, dont l'aspect (alignement, espacement) peut etre fait facilement et en un seul coup pour chaque type de situation.
