### ISSUE TITLE
Réorganisation du dépot

### ISSUE THREAD

**Issue by LaurentClaessens** [LaurentClaessens/mazhe#25]
J'ai encore envie de simplifier l'organisation des répertoires.

Proposition 

* Un répertoire `tex` qui contient les fichiers `tex`  (à l'exclusion de ceux qui sont générés automatiquement pour les figures). Il serait divisé en
   * frido
   * research
   * exercices/correction
   * les sources des petits exemples de code inclus dans le texte (sage, python, matlab)
   * etc.

* Un répertoire `manuel du contributeur`
* Un répertoire `auto` qui contiendrait les fichiers générés automatiquement : le code `tikz` des figures, ainsi que leurs `md5` et `pdf`. C'est le répertoires des choses auxquelles il ne faut pas toucher.
* Un répertoire `src_phystricks` contenant les sources des figures.

**Comment by Naereen** [comment]
C'est une bonne idée. Bon courage :+1: !

**Comment by Naereen** [comment]
:+1:
