### ISSUE TITLE
Automorphisme du corps R

### ISSUE THREAD

**Issue by LaurentClaessens** [LaurentClaessens/mazhe#26]
Soit l'énoncé «L'unique automorphisme du corps R est l'identité».
Est-ce que pour vous il y a dans cet énoncé un implicite comme quoi on n'a le droit de le prouver qu'en utilisant la structure de coprs de R ?

Moi j'ai la ferme impression que l'énoncé tel quel autoriste l'utilisation de toute la structure de R, mais [ce n'est pas le cas de tout le monde](http://forums.futura-sciences.com/mathematiques-superieur/261451-automorphisme-de-r-continuite.html).

Quel est l'usage dans les cours d'algèbre ?

**Comment by Naereen** [comment]
J'ai la même impression que toi.

D'autant que je ne vois pas comment généraliser ce résultat à un "corps quelconque qui aurait la même structure que R mais pas ses propriétés particulières" ?

**Comment by LaurentClaessens** [comment]
On peut parler du [foncteur d'oubli](https://fr.wikipedia.org/wiki/Foncteur) ;)

Sinon on peut écrire «Soit K un corps isomorphe à R (en tant que corps). Tout automorphisme de K est l'identité».
Ou alors simplement dire oralement aux étudiants : «lorsqu'on parle d'un corps, on n'a le droit de n'utiliser que les concepts de corps».

Je vois bien le pauvre étudiant qui le prend un peu trop au sérieux et qui n'utilise que la structure topologique de R pour parler de fonctions continues (et donc pas le critère avec la limite).

**Comment by Naereen** [comment]
Je vois.
