### ISSUE TITLE
Liste des auteurs/contributeurs

### ISSUE THREAD

**Issue by LaurentClaessens** [LaurentClaessens/mazhe#32]
Pour l'instant, je tiens à jour une liste des personnes qui ont contribué dans la section « Auteurs, contributeurs, sources et remerciements». Cette liste est pour l'instant à la page 69, au début de l'introduction, après les index, tables des matières et tout ça.

Je me demande si il ne faudrait pas aller un peu plus loin et directement écrire sur la page de couverture le nom au moins des personnes ayant produit un patch[1], c'est à dire celles qui ont effectivement produit du texte.

En tout cas, n'hésitez pas à ajouter vos noms là où vous avez contribué ou sur la page de titre.

[1] en évitant l'humour de matheux avec le patch auto-référentiel qui consiste à ajouter son nom.

**Comment by Naereen** [comment]
Via les logs des commits sur GitHub tu peux très facilement récupérer les pseudos des gens ayant contribués; par exemple:
```bash
$ git shortlog -sn --all | cut -f2
Superman
Batman
Cendrion
```

Par contre il faudra sûrement éditer ça à la main pour mettre leur nom et pas juste un pseudo GitHub.

> [1] J'imagine bien la prochaine version imprimée, 3800 pages dont 2400 pages d'une liste sans fin de faux contributeurs!

**Comment by LaurentClaessens** [comment]
Mon point n'était pas tellement la difficulté de trouver le nom des personnes (ou au moins leurs pseudos), mais surtout le fait que je ne me la sentait pas de mettre moi-même un nom en couverture sans l'accord des personnes.

**Comment by Naereen** [comment]
Ah, oui. Je comprends mieux.
Moi je suis d'accord, et je pense que le plus simple est que tu fasses toi-même une Pull Request d'ajout du nom de chaque contributeur, en le notifiant (e.g., @Naereen) dans le commentaire.
Si pas de réponse, non, si réponse positive, tu merges.
