### ISSUE TITLE
Liens morts: sources 13 et 15 (au moins)

### ISSUE THREAD

**Issue by bibi6** [LaurentClaessens/mazhe#34]
Le lien de la source 13 est mort... enfin, les pages perso SFR ont disparu en novembre 2016.

**Comment by Naereen** [comment]
(je ne sais pas à quoi vous faites référence)

Mais les pages en question sont peut-être encore accessibles sur des sites d'archivages, comme https://web.archive.org/ ou le cache utilisé par Wikimédia, http://archive.wikiwix.com/ ?

(conseil général @LaurentClaessens : un lien utile peut être sauvegardé en un clic sur https://web.archive.org, ça peut aider pour des références que tu n'as que comme lien web)

**Comment by Naereen** [comment]
@bibi6 : continuez dans votre lancée, c'est très utile ! (je manque de temps pour relire le Frido depuis quelques temps...)

**Comment by LaurentClaessens** [comment]
Le 22/05/2017 à 22:19, Lilian Besson a écrit :
> (je ne sais pas à quoi vous faites référence)
> 
> Mais les pages en question sont peut-être encore accessibles sur des sites d'archivages, comme https://web.archive.org/ ou le cache utilisé par Wikimédia, http://archive.wikiwix.com/ ?
> 
> (conseil général @LaurentClaessens : un lien utile peut être sauvegardé en un clic sur https://web.archive.org, ça peut aider pour des références que tu n'as que comme lien web)
> 

Oui, ces liens morts sont une plaie. Quelque réflexions autour de cela...

* Lorsqu'on énonce un résultat sans donner la preuve, il faut mettre un 
lien vers une ressource en ligne qui contient la preuve.

* A priori, dans la biblio, il vaut mieux mettre le lien original parce 
que ça crée du trafic vers l'auteur, et c'est bon pour lui.

* Si un auteur veut dépublier, c'est son droit, même si ça cause des 
liens morts chez les autres.

* N'y a-t-il pas des problèmes de droits d'auteurs à archiver 
systématiquement chez web.archives.org ? Je pense par exemple à celui-ci :
http://tanopah.jo.free.fr/epilogues/reduction.pdf
Je ne sais pas pour la légalité stricte, mais du point de vue de la 
volonté de l'auteur, au moins le gars s'exprime clairement.

* D'après la FAQ de web.archives.org, ils archivent tout sauf demande 
expresse de l'auteur (par exemple via un fichier robot.txt). La légalité 
de cela devrait être discutée un vendredi sur linuxfr.

* Bien entendu, j'ai sur mon ordinateur une copie de presque tous les 
documents cités dans la biblio du Frido (ça ne veut cependant pas dire 
que je les retrouverais facilement).

* À mon avis le bon moyen serait de contacter chaque auteur en demandant :
  1. si il a remis son texte quelque part d'autre
  2. si il est d'accord que nous en remettons une copie quelque part, 
pour la citation.

* D'un point de vue strictement narcissique, l'avantage de demander est 
que ça permet de passer une pub en douce pour le Frido à 13 personnes 
sélectionnées pour avoir déjà mis des textes de math en ligne.


Dans un élan de lyrisme futuriste, je dirais que la bonne solution 
serait que les gens publient leurs textes dans la chaîne de blocs 
distribuée des publications mathématiques.

**Comment by Naereen** [comment]
OK je suis d'accord avec tout.

C'est assez compliqué ces hstoires de droit de copie et d'archivage. La mission de archive.org est noble mais risquée.
Je pense que ton approche est donc la bonne.

**Comment by LaurentClaessens** [comment]
@bibi6 : est-ce que tu peux donner la liste des liens morts que tu as trouvé ?

Je crois qu'il faudra scripter une recherche de \url et \href.

Si tu as écrit un script qui parse `mazhe.bib`, tu peux le mettre dans le répertoire "testing". Je suis en train d'y rassembler quelque scripts de vérification automatique de différentes choses (intégrité des figures et références vers le futur principalement).

**Comment by Naereen** [comment]
C'est rapide et sûrement insuffisant, mais voici un début :
```bash
#!/usr/bin/env bash
# test-url-in-file
for file in $@; do
    egrep -o "\\url\{([^\}]+)" "$file" | sed s/"\\url{"/""/g | test-all-urls.sh
    egrep -o "\\href\{([^\}]+)" "$file" | sed s/"\\url{"/""/g | test-all-urls.sh
done
```
et
```
#!/usr/bin/env bash
# test-all-urls.sh
cd /tmp/
for url in $@; do
    wget --quiet "$url" || echo -e "$url invalide ?"
done
```
C'est très brouillon mais ça donne l'idée.

Cela dit je pense que ça existe déjà, probablement en Python.

**Comment by LaurentClaessens** [comment]
Qu'il existe en python un moyen de savoir si une URL n'est pas un 404 ne fait aucun doute.
Par contre, je ne suis pas certain qu'il existe des moyens tout faits en python pour parser du LaTeX.

Je me rends compte pour l'occasion que 'mazhe.bib' contient plein d'hyperliens dans les champs "note" au lieu de "url". Il faudrait unifier cela ...

**Comment by bibi6** [comment]
> @bibi6 : est-ce que tu peux donner la liste des liens morts que tu as trouvé ?

À vrai dire, c'est juste que je pensais consulter la réf... du coup, je n'ai détecté que celle-là, et manuellement ;)

**Comment by LaurentClaessens** [comment]
Le `wget --quiet` est inefficace parce qu'il télécharge effectivement tout ce que contient l'URL.

En python on peut faire sans télécharger :

https://stackoverflow.com/questions/6471275/python-script-to-see-if-a-web-page-exists-without-downloading-the-whole-page 

Les `egrep` par contre me semblent plus concis que ce que je pourrais faire en python.

- Des `ls` en bash pour avoir la liste des fichiers
- Passage à `egrep` pour créer la liste des URL
- Passage à python pour vérifier si elles sont bonnes.

Avec ça, on n'a pas encore les URL dans les champs `url = "...." ` de mazhe.bib
Attention : je ne jurerais pas qu'aucune URL ne contienne un " 
La dernière contient même une parenthèse non fermée.

**Comment by Naereen** [comment]
OK

- Je recommande `find . -type f` plutôt que `ls`
- Le `egrep` que j'ai fait est très sommaire
- OK en Python

**Comment by bibi6** [comment]
Comme updaté, le lien de la source 15 aussi, est mort :(

**Comment by bibi6** [comment]
Le 21 aussi.

**Comment by LaurentClaessens** [comment]
Ce sont les références aux doux noms de :

- PDFpersoWanadoo
- BezoutCos
- NjCCfW

Pour l'instant je ne les corrige pas, et les tiens en mémoire comme "test" pour le futur détecteur de liens morts en cours de rédaction ...

**Comment by LaurentClaessens** [comment]
J'ai poussé un premier détecteur d'url mort dans la branche alpha.

**Comment by Naereen** [comment]
Ça marche chez moi ! :+1:
Par contre ça ne cherchait pas à vérifier si les liens sont valides comme prévu.

J'espère que https://github.com/LaurentClaessens/mazhe/pull/39 aidera.

**Comment by LaurentClaessens** [comment]
Je viens de pousser dans 'alpha' une violente purge de 'mazhe.bib'. j'ai supprimé pas mal de \cite.

J'ai pu retrouver quelque documents qui avaient bougé et contacté deux ou trois auteurs.

Mais là je dois avouer que la tâche est démesurée : j'ai encore 27 url cassées. Je crois que c'est un peu idiot de persévérer à tenter de retrouver soit le texte soit l'auteur pour chaque : au final il est sûrement plus simple de trouver une autre source pour les résultats énoncés et qui sont maintenant sans citations.

**Comment by Naereen** [comment]
Effectivement...

Je ne me souviens pas d'en avoir vue il y a 3 ans... mais encore une fois je n'ai plus trop utilisé le Frido depuis 2014 :cry:

**Comment by LaurentClaessens** [comment]
Un nettoyage a été fait, le détecteur d'url cassées fonctionne à peu près (on pourrait beaucoup paralléliser).

J'attends la réponse de quelque personnes pour savoir où retrouver leurs textes, et on relacera de temps en temps les tests. Il se lance avec
```
<mazhe>/testing/testing.sh --dead-links
```
