### ISSUE TITLE
Référence manquante (Chapitre 41 Épilogue : la constante de Weiner)

### ISSUE THREAD

**Issue by matheod** [LaurentClaessens/mazhe#44]
Bonjour,

Juste pour signaler qu'il manque une référence dans le chapitre 41 (p1835) deuxième ligne : 
> En guise de conclusion, je voudrais vous parler de la constante de Weiner, introduite dans [].

edit : bonus : 

> La moyenne de tout couple de réels peut être calculée !!!**_ne_**!!! divisant leur somme par la
> constante de Weiner 2.
> 

edit : oh, je viens de lire et de comprendre

**Comment by LaurentClaessens** [comment]
Référence ajoutée, et publiée dans la branche 'alpha'. L'article de haut vol proposant de nommer la constante de Weiner est celui-ci
http://www.smbc-comics.com/comic/2008-02-21
