### ISSUE TITLE
Quelques typos du chapitre 2

### ISSUE THREAD

**Issue by ybailly** [LaurentClaessens/mazhe#45]
Dans le chapitre "Construction des ensembles de nombres":

- 2.1 "Quelques éléments sur les ensembles", "...une théorie naïve des ensemble comme..." : "s" à "ensembles"
- Définition 2.5 "..est un minimum si... m est comparable à m et m <= y" : un "m" n'est-il pas de trop et devrait devenir "y" ?
- Définition 2.13 : comment se lit (prononce) le "delta" ?
- Lemme 2.14, démonstration, "...séparant les cas suivant que...": "s" à "suivants"
- même phrase, "B inclus à A"... ? plutôt "B inclus dans A" ?
- 2.2.2 "Quelques autres résultats", "...implications comme a > b implique qu'il n'existe pas de x tel que a+b=b" : plutôt "a+x=b" ?
- 2.4 "Quelques structures algébriques", définition 2.20 "..est un groupe abélien" : cela a-t-il été défini auparavant ?

Plus à venir...

**Comment by LaurentClaessens** [comment]
Le 27/09/2017 à 19:46, ybailly a écrit :
> Dans le chapitre "Construction des ensembles de nombres":
> 
> - 2.1 "Quelques éléments sur les ensembles", "...une théorie naïve des ensemble comme..." : "s" à "ensembles"

Bien vu.

> - Définition 2.5 "..est un minimum si... m est comparable à m et m <= y" : un "m" n'est-il pas de trop et devrait devenir "y" ?



> - Définition 2.13 : comment se lit (prononce) le "delta" ?

Il se prononcer "différence symétrique". C'est vrai que "a U b" peut se 
prononcer en lisant de gauche à droite "a union b", mais effectivement 
pour la différence symétrique, il faut faire une périphrase pour lire : 
'a \Delta b' doit se lire "la différence symétrique entre a et b".

> - Lemme 2.14, démonstration, "...séparant les cas suivant que...": "s" à "suivants"

Ici "suivant" n'est pas un adjectif de "cas". Mais c'est vrai que la 
formulation n'est pas top.
Je reformule.

> - même phrase, "B inclus à A"... ? plutôt "B inclus dans A" ?

Effectivement...
Ack me retourne 32 occurrences de "inclus à".


> - 2.2.2 "Quelques autres résultats", "...implications comme a > b implique qu'il n'existe pas de x tel que a+b=b" : plutôt "a+x=b" ?

oui

> - 2.4 "Quelques structures algébriques", définition 2.20 "..est un groupe abélien" : cela a-t-il été défini auparavant ?


Il n'y avait même pas de définition d'un groupe. C'est ajouté.

Merci


> Plus à venir...
>
