### ISSUE TITLE
Rendre la compilation plus simple

### ISSUE THREAD

**Issue by LaurentClaessens** [LaurentClaessens/mazhe#51]
Pour l'instant pour contribuer de manière plus ou moins vivable (c'est à dire sans faire `pdflatex mazhe.tex` pour compiler chaque virgule), il faut :

* git pull de mazhe, latexparser et pytex
* faire voir latexparser dans la variable d'environnement 'PYTHONPATH'
* faire voir pytex dans PATH
* et là c'est bon

Il y a sûrement moyen de rendre plus simple.

Je propose : un script `install.sh` qui 
* fait les `git pull` de latexparser et pytex vers des sous-répertoires de `mazhe`
* copie l'exécutable `pytex` vers le répertoire `mazhe` et le modifie à la volée pour qu'il aille chercher ses `import` dans les bons répertoires.

Perso j'adore l'idée écrire du code bash dont le but est de générer du code python qui a pour finalité de créer le code latex qui servira à produire un pdf.

**Comment by ericguirbal** [comment]
Je suis justement en train de faire un Makefile.

**Comment by LaurentClaessens** [comment]
Un makefile peu faire l'affaire pour parer au plus pressé (typiquement : ne compiler que quelque fichiers). Mais pour avoir toutes les fonctionnalités, le cahier des charges est lourd; je serais étonné qu'on puisse le faire sans passer  par un vrai langage de programmation.

* possibilité de changer à la volée les lignes `\boolfalse{isFrido}` en `\booltrue{isFrido}`
* hacker le fichier `.toc` pour mettre le numéro de volume (division calculée à la volée basée sur le nombre de pages) à côté des titres de chapitres
* modifier la ligne `\newcommand{\GitCommitHexsha}{\info{missing information}}` pour y mettre le numéro de commit courant.
* demander à `pdflatex` de compiler vers un fichier `foo.pdf` (nom dépendant de la configuration) et de copier après la compilation vers `0-foo.pdf` (et le fichier synctex.gz correspondant). Le but de ce point est que le lecteur de pdf ne se mette pas en mode "rafraîchissement" tout au long de la compilation tout en se rafraîchissant automatiquement lorsque c'est terminé.

**Comment by truatpasteurdotfr** [comment]
- possibilité de changer à la volée les lignes \boolfalse{isFrido} en \booltrue{isFrido}
```
|sed 's,boolfalse{isFrido},booltrue{isFrido},g'
```

**Comment by truatpasteurdotfr** [comment]
- modifier la ligne \newcommand{\GitCommitHexsha}{\info{missing information}} pour y mettre le numéro de commit courant.
```
| sed "s,info{missing information}},info{"`git log| sed -n '1p'| cut -d ' ' -f 2`"}},g"
```
