### ISSUE TITLE
Question (8) d'algèbre/géométrie : lemme 5.43 sur les PGCD de polynômes.

### ISSUE THREAD

**Issue by cdrcprds** [LaurentClaessens/mazhe#52]
Le lemme 5.43 à propos des PGCD de polynômes est correct.
Le polynôme pgcd(P,PU+R) ne dépend effectivement pas de U : il vaut pgcd(P,R).

J'ai toutefois émis avant chaque démonstration quelques remarques sur les deux points du lemme.
Les démonstrations sont somme toute assez simples.

**Premier point du lemme**

Soit $P,Q,R\in K[X]$ des polynômes tels que $P$ soit premier avec $Q$. Alors $pgcd(P,QR)=pgcd(P,Q)pgcd(P,R)$

**Remarques avant la démonstration**

Puisque $P$ et $Q$ sont premiers entre eux, on a : $pgcd(P,Q)=1$ et il n'est donc pas très utile de faire figurer ce PGCD dans la formule donnée par le lemme...
Elle se réécrit donc : $pgcd(P,QR)=pgcd(P,R)$.

Dans ma démonstration de ce premier point, j'utilise le théorème de Gauss... qui est situé juste en-dessous du lemme.
Il faudra donc soit adapter un peu la démonstration, soit changer l'organisation du cours pour placer ce lemme après le-dit théorème.

**Démonstration**

Montrons que pour tout polynôme $A$ de $\mathbb{K}[X]$ :
$A|\{P,QR\} \Leftrightarrow A|\{P,R\}$

Sens $\Rightarrow$ :
Par hypothèse, il existe des polynômes $U,V,B_1,B_2$ tels que $PU+QV=1$, $P=AB_1$ et $QR=AB_2$
Montrons que $A|R$ :
$A|P$ et $P$ est premier avec $Q$, donc $A$ est premier avec $Q$
(En effet : $A(B_1U)+QV=1$ donc d'après le théorème de Bézout, $A$ et $Q$ sont premiers entre eux)
$A|QR$ et $A$ est premier avec $Q$ donc d'après le théorème de Gauss : $A|R$

Sens $\Leftarrow$ :
Si $A|R$ alors on a évidemment : $A|QR$

Bilan :
Les diviseurs de $\{P,QR\}$ sont exactement les diviseurs de $\{P,R\}$
Les paires $\{P,QR\}$ et $\{P,R\}$ ont donc le même PGCD.

**Second point du lemme**

En analogie avec le lemme 3.37, nous avons $pgcd(P,PQ+R)=pgcd(P,R)$

**Remarque avant la démonstration**

Le fait qu'aucune hypothèse sur $P,Q,R$ ne soit précisée dans ce second point laisse penser que les hypothèses sont les mêmes que pour le premier point.
En réalité, il n'est ici absolument pas nécessaire que $P$ soit premier avec $Q$ : $P,Q,R$ sont des polynômes quelconques.

**Démonstration**

Montrons que pour tout polynôme $A$ de $\mathbb{K}[X]$ :
$A|\{P,PQ+R\} \Leftrightarrow A|\{P,R\}$

Sens $\Rightarrow$ :
Par hypothèse, il existe des polynômes $B_1,B_2$ tels que $P=AB_1$ et $PQ+R=AB_2$
Montrons que $A|R$ :
$R=(PQ+R)-PQ=(AB_2)-(AB_1)Q=A(B_2-B_1Q)$ donc $A|R$

Sens $\Leftarrow$ :
Par hypothèse, il existe des polynômes $B_1,B_2$ tels que $P=AB_1$ et $R=AB_2$
Montrons que $A|PQ+R$ :
$PQ+R=(AB_1)Q+(AB_2)=A(B_1Q+B_2)$ donc $A|PQ+R$

Bilan :
Les diviseurs de $\{P,PQ+R\}$ sont exactement les diviseurs de $\{P,R\}$
Les paires $\{P,PQ+R\}$ et $\{P,R\}$ ont donc le même PGCD.

**Comment by cdrcprds** [comment]
Après réflexion, il y a peut-être une coquille dans les hypothèses du premier point du lemme.
Les polynômes premiers entre eux ne seraient pas P et Q, mais Q et R.

Si Q et R sont premiers entre eux, on a bien : pgcd(P,QR)=pgcd(P,Q)pgcd(P,R)

La démonstration me paraît cependant moins immédiate.
On s'en sort assez facilement en utilisant des décompositions en produit de polynômes irréductibles, mais je ne vois pas d'autre façon de procéder.

**Comment by LaurentClaessens** [comment]
Il y a effectivement deux énoncés non équivalents possibles. On va mettre les deux.
Je pousse dans la branche 'alpha'.

**Comment by LaurentClaessens** [comment]
Chez moi ça marche(tm).
C'est publié à la page 188.
Est-ce qu'il y a une faute dans un des trois cas ?

**Comment by cdrcprds** [comment]
Pas de fautes dans le lemme, mais quelques coquilles dans les démonstrations :

**Pour le point (1)**

A | {P,PQ+R} implique A| | {P,R}
=> Il y a une barre verticale en trop.

A | {P,R} implique A| | {P,PQ+R}
=> Même chose.

**Pour le point (3)**

Le point (3) est démontré deux fois...

Ce la prouve que A est premier avec Q grâce encore à Bérout, mais dans l’autre sens.
=> "Cela" en un seul mot, "Bézout" avec un 'z'

Conclusion : Nous avons Les diviseurs de P,QR sont exactement les diviseurs de P,R.
=> Le début de la phrase est à revoir.
=> Les accolades autour de chaque paire de polynômes ne sont pas visibles.

En conséquence de quoi nous concluons que les paires P,QR et P,R ont le même pgcd.
=> Même chose pour les accolades.

Maintenant vous devriee être capables de faire ça.
=> "devriez"

**Comment by LaurentClaessens** [comment]
> **Pour le point (3)**

Effectivement. Et le point (2) est celui qui semble un peu plus 
résistant que les deux autres ...

**Comment by cdrcprds** [comment]
Une démonstration du point (2) qui s'appuie sur deux propriétés assez faciles à établir :
(je ne sais pas si ces propriétés figurent dans le Frido, mais ça ne coûterait pas cher de les ajouter si elles n'y sont pas déjà)


**Première propriété :** (c'est une conséquence du théorème de Bézout)
$A,B$ sont deux polynômes quelconques, $G$ est un polynôme unitaire.
$G$ est *le* pgcd de $A$ et $B$ si et seulement si les deux conditions suivantes sont vérifiées :
- il existe deux polynômes $U$ et $V$ tels que $AU+BV=G$
- $G|A$ et $G|B$

(si on ne suppose pas $G$ unitaire, alors $G$ ne sera pas *le* pgcd mais *un* pgcd)

**Démonstration :**

Sens $\Rightarrow$ :

Si $G$ est le pgcd de $A$ et $B$, il est clair que $G|A$ et $G|B$.
Il reste donc à montrer l'existence des polynômes $U$ et $V$ vérifiant $AU+BV=G$.
Il existe des polynômes $A_1,B_1$ tels que $A=GA_1$ et $B=GB_1$.

On montre facilement que les polynômes $A_1$ et $B_1$ sont premiers entre eux :
S'ils ont un diviseur commun $D$, alors $GD$ est un diviseur commun à $A$ et $B$.
Or, $G$ est le pgcd de $A$ et $B$ donc $GD|G$ ; $D$ ne peut être qu'un polynôme constant.
$A_1$ et $B_1$ sont donc bien premiers entre eux.

D'après le théorème de Bézout, il existe donc $U$ et $V$ tels que $A_1U+B_1V=1$.
En multipliant par $G$, on obtient l'égalité voulue : $AU+BV=G$.

Sens $\Leftarrow$ :

Si $G$ vérifie les deux conditions, montrons que $G$ est un/le pgcd de $A$ et $B$ :
On sait déjà (par hypothèse) que $G$ divise $A$ et $B$, il reste à montrer que tous les diviseurs commun à $A$ et $B$ divisent aussi $G$.
Soit donc $D$ un diviseur commun à $A$ et $B$ :
Il existe $A_1$ et $B_1$ tels que $A=DA_1$ et $B=DB_1$.
On sait que $G=AU+BV$ donc $G=D(A_1U+B_1V)$, et $D|G$.

Par définition, $G$ est bien un/le pgcd de $A$ et $B$.


**Deuxième propriété :** (c'est une conséquence du théorème de Gauss)
$A,B$ sont deux polynômes premiers entre eux, $P$ est un polynôme quelconque.
Si $P$ est divisible par $A$ et par $B$ alors $P$ est divisible par $AB$.

**Démonstration :**

$A$ divise $P$ donc il existe $Q_1\in\mathbb{K}[X]$ tel que $P=AQ_1$.
$B$ divise $P=AQ_1$, et $B$ est premier avec $A$ donc d'après le théorème de Gauss : $B|Q_1$.
Il existe donc $Q_2\in\mathbb{K}[X]$ tel que $Q_1=BQ_2$.
On a donc $P=ABQ_2$ : $P$ est bien divisible par $AB$.


*On peut maintenant passer à la démonstration du fameux point (2) :*

On a trois polynômes $P,Q,R$ et on sait que $Q$ et $R$ sont premiers entre eux.
On note : $G_1=pgcd(P,Q)$ et $G_2=pgcd(P,R)$.
Il faut montrer que $G_1G_2$ est le pgcd de $P$ et $QR$.
Pour utiliser la **première propriété**, on a deux choses à montrer :

- Montrons qu'il existe des polynômes $U$ et $V$ tels que $G_1G_2=PU+QRV$ :
$G_1=pgcd(P,Q)$ donc il existe $U_1$ et $V_1$ tels que $G_1=PU_1+QV_1$ (on utilise pour cela la **première propriété**).
On a de même : $G_2=PU_2+RV_2$.
$G_1G_2=(PU_1+QV_1)(PU_2+RV_2)$. En développant, on trouve :
$G_1G_2=PU+QRV$ avec $U=PU_1U_2+QV_1U_2+RU_1V_2$ et $V=V_1V_2$.

- Montrons que $G_1G_2$ divise $P$ et $QR$ :
$G_1|Q$ et $G_2|R$ donc $G_1G_2|QR$.
Il reste à montrer que $G_1G_2|P$ :
$P$ est divisible par $G_1$ et par $G_2$ ; et on vérifie facilement que $G_1$ et $G_2$ sont premiers entre eux (si $D$ est un diviseur commun à $G_1$ et $G_2$, alors $D$ divise $Q$ et $R$ qui sont premiers entre eux ; $D$ ne peut être qu'un polynôme constant).
On peut donc utiliser la **deuxième propriété** pour conclure que $P$ est divisible par $G_1G_2$.

Les deux conditions citées dans la **première propriété** sont remplies, $G_1G_2$ est bien le pgcd de $P$ et $QR$.


Voilà, avec tout ça, je pense que la question qui restait en suspens est close :)

**Comment by LaurentClaessens** [comment]
Merci. Je vais essayer de taper ça.
Pour l'instant j'ai des problèmes de connexion, alors je ne suis pas 
très réactif.
