### ISSUE TITLE
Soit : accord ou pas

### ISSUE THREAD

**Issue by ericguirbal** [LaurentClaessens/mazhe#56]
On peut aussi bien écrire « Soit $f$ et $g$ deux fonctions » que « Soient f$ et $g$ deux fonctions ».
Manifestement tu n'as pas fait ton choix :-) Il serait bien, dans un soucis de consistance, qu'un choix soit fait.
Sans vouloir t'influencer, je note que dans ma bibliothèque, presque tous les auteurs font l'accord (à l'exception d'Arnaudiès et Fraysse dans leur manuel de prépa).

**Comment by LaurentClaessens** [comment]
Pluriel.
Ne pas confondre «je n'ai pas fait mon choix» avec «je n'ai pas été fichu de le tenir» :)
