### ISSUE TITLE
L'exemple 4.84 est faux : Z est principal

### ISSUE THREAD

**Issue by cdrcprds** [LaurentClaessens/mazhe#58]
L'exemple 4.84 affirme que Z n'est pas principal (et donc pas euclidien non plus).

**Exemple 4.84** (Z n’est ni principal ni euclidien)
_L’idéal (2) = 2Z n’est pas un idéal principal de Z, parce que tout multiple entier d’un nombre
pair reste pair. Donc Z possède des idéaux non principaux et n’est pas conséquent pas un anneau
principal.
Il ne peut alors pas non plus être euclidien par la proposition 4.83._

Pourtant, Z est principal (c'est d'ailleurs bien précisé dans l'exemple 4.71) et même euclidien (la valeur absolue sur Z est bien un stathme euclidien).
L'idéal 2Z est en tout état de cause principal, puisqu'il est engendré par 2.

Cet exemple est donc à supprimer/remplacer ; [wikipédia](https://fr.wikipedia.org/wiki/Anneau_principal#Contre-exemples) donne des exemples d'anneaux intègres non principaux (et donc non euclidiens) qui seraient plus judicieux : Z[i\sqrt{5}] ou alors A[X] (où A est un anneau intègre qui n'est pas un corps).

La remarque en-dessous de l'exemple 4.82 ("_L’exemple 4.84 montrera que Z ne possède pas de stathme euclidien en montrant qu’il n’est pas principal._") devra aussi être revue en conséquence.

**Comment by LaurentClaessens** [comment]
Merci pour la détection de faute (et pour toutes les réponses aux 
questions).
Je vais tâcher de tenir compte de tout ça dans les jours à venir.

J'aurais dû directement mettre en ligne un "errata.pdf" (tout blanc au 
départ) et mettre un lien dans le Frido.

**Comment by LaurentClaessens** [comment]
J'ai poussé une correction avec preuve que Z[X] est euclidien et principal dans la branche alpha. Ça devrait arriver dans master dans pas très longtemps.
Par contre, ma connexion internet fonctionne très mal depuis un mois, et ça risque de prendre par mal de temps avant que je puisse publier le pdf corrigé.
(en gros : le temps que je trouve le temps d'aller voir mon opérateur pour résilier l'abonnement et d'en ouvrir un autre)

**Comment by cdrcprds** [comment]
> J'ai poussé une correction avec preuve que Z[X] est euclidien et principal dans la branche alpha. 

Je suppose que tu veux dire Z ?

Dans un de tes commits, tu poses la question pour Z[X] : lui n'est ni euclidien ni principal.

Le lien [wikipédia](https://fr.wikipedia.org/wiki/Anneau_principal#Contre-exemples) que j'ai mentionné plus haut explique que si l'anneau intègre A n'est pas un corps, l'idéal de A[X] engendré par X et a (où a est un élément non inversible de l'anneau A) n'est pas principal.
On peut appliquer ce raisonnement pour Z[X] en prenant par exemple a=2.

**Comment by LaurentClaessens** [comment]
Le 24/10/2017 à 17:26, cdrcprds a écrit :
>> J'ai poussé une correction avec preuve que Z[X] est euclidien et principal dans la branche alpha. 
> 
> Je suppose que tu veux dire Z ?

Oui.
Ouf.

> 
> Dans un de tes commits, tu poses la question pour Z[X] : lui n'est ni euclidien ni principal.

> Le lien [wikipédia](https://fr.wikipedia.org/wiki/Anneau_principal#Contre-exemples) que j'ai mentionné plus haut explique que si l'anneau intègre A n'est pas un corps, l'idéal de A[X] engendré par X et a (où a est un élément non inversible de l'anneau A) n'est pas principal.
> On peut appliquer ce raisonnement pour Z[X] en prenant par exemple a=2.

Il est excellent cet article. Je vais tout pomper jusqu'à l'exemple des 
fonctions holomorphes sur un compact inclusivement.

**Comment by cdrcprds** [comment]
J'ai relu les preuves des points 4.85 et 4.86, il y a deux-trois trucs à corriger :

**4.85**
_L’anneau Z est principal et euclidien._

La démonstration contient des "copier-coller" dont il reste des déchets : il faut supprimer _"et le couple (q_0,r_0)"_ dans les trois derniers cas.

**4.86**
_Si A est un anneau intègre qui n’est pas un corps, alors A[X] n’est pas principal._

- Dans la première partie de la démonstration, on arrive à l'égalité kk'=1.
À partir de là, on peut seulement en déduire que k est inversible (pas nécessairement égal à 1 ou -1).
Néanmoins, le fait que k soit inversible est suffisant pour la suite : si l'idéal contient un inversible, alors cet idéal est en fait l'anneau A[X] tout entier.

- À la fin de cette même première partie : (P) n'est pas égal à A mais à A[X] (il manque donc le "[X]")

**Comment by LaurentClaessens** [comment]
J'ai poussé un gros morceau qui répond à toutes les remarques de ce fil. Espérant que je n'ai pas ajouté trop de bêtises au passage.

Au passage j'ai découvert une autre faure : il était prétendu que les Z/nZ sont principaux. Vive la page de wikipédia qui prend justement Z/nZ comme exemple d'un anneau non principal dont tous les idéaux sont principaux.
