### ISSUE TITLE
Tutoiement/vouvoiement

### ISSUE THREAD

**Issue by cdrcprds** [LaurentClaessens/mazhe#59]
Le lecteur est parfois tantôt tutoyé (j'ai vu plusieurs tutoiements notamment dans le chapitre 12), tantôt vouvoyé.
À mon avis, il serait bon d'éviter le tutoiement et de s'en tenir au vouvoiement.

**Comment by LaurentClaessens** [comment]
Pour l'avenir, ok. Mais pour l'existant ... j'ai fait un `ack " tu "` et ce que j'ai vu m'a découragé.

**Comment by LaurentClaessens** [comment]
En fait le tutoement massif du chapitre 12 en particulier est dû au fait que ce chapitre est à la base une récupération d'un cours de physique que j'avais écrit pour les enfants plus jeunes.
http://laurent.claessens-donadello.eu/pdf/echa.pdf

Le même phénomène est à l'oeuvre, pour la même raison dans la partie sur la relativité (chapitre "Utilisation dans les autres sciences")
