### ISSUE TITLE
Questions (9), (15) et (21) d'algèbre

### ISSUE THREAD

**Issue by cdrcprds** [LaurentClaessens/mazhe#60]
**Question 9**
_Est-ce que l’énoncé et la démonstration de la proposition 5.67 sont corrects ? Si a et b sont des racines de P, alors µaµb divise P (si µa!=µb) Cette proposition est utilisée dans la démonstration de l’irréductibilité des polynômes cyclotomiques (proposition 5.125)._

La démonstration est correcte, mais on peut la rendre un peu plus élégante, en utilisant la proposition 5.54 qui nous apprend que µ_a est irréductible sur le corps K.

La partie concernée est l'avant-dernier paragraphe de la démonstration, où on justifie que µ_a(b) n'est pas nul.
On y suppose par l'absurde que µ_a(b) = 0, puis on écrit : µ_a = µ_b * R.
Je trouve que la suite de ce paragraphe est un peu confuse, je propose donc de la remplacer par quelque chose comme :

Puisque µ_a est irréductible, l'égalité µ_a = µ_b * R n'est possible que si µ_b ou R est un polynôme constant.
R est donc un polynôme constant (égal à 1 puisque µ_a et µ_b sont unitaires) et on obtient : µ_a = µ_b (ce qui est en contradiction avec les hypothèses du théorème)

**Question 15**
_Pourquoi la pseudo-réduction simultanée (corollaire 9.174) est-elle pseudo ? Pourtant les
matrices sont bel et bien simultanément diagonalisées._

Il s'agit d'une _pseudo-réduction_ tout simplement parce que les matrices ne sont pas vraiment diagonalisées.

La matrice Q n'est a priori pas orthogonale, sa transposée n'est donc pas égale à son inverse...
Contrairement aux apparences, il ne s'agit donc pas d'une vraie diagonalisation.

**Question 21**
_Si f : V -> V est une application linéaire, on ne peut pas définir la transposée f^t : V -> V comme étant l’application linéaire dont la matrice est la transposée de la matrice de f parce que cette définition n’est pas invariante par changement de base. C’est vrai ? Voir le problème 8._

La définition par transposition de matrice n'est effectivement pas invariante par changement de base, comme on peut le vérifier sur un exemple simple (ici, en dimension 2) :

On considère une base B=(e1,e2) et l'application linéaire f définie par :
f(e1)=e1 et f(e2)=0

La matrice de f dans la base B est : \begin{pmatrix}1 & 0\\0 & 0\\\end{pmatrix}
C'est une matrice symétrique, donc **dans cette base** f est égale à sa transposée.

On considère maintenant la base B'=(e1,e1+e2)
Les vecteurs de la base B' ont pour image : f(e1)=f(e1+e2)=e1
La matrice de f dans la base B' est donc : \begin{pmatrix}1 & 1\\0 & 0\\\end{pmatrix}

Ce n'est plus une matrice symétrique.
Dans cette base, la transposée de f est donc une application différente de f.

**Comment by cdrcprds** [comment]
J'en profite pour répondre aussi à la **question (17)** :
_Est-ce que la proposition 5.54 disant qu’un polynôme minimal est irréductible et premier avec tout polynôme non annulateur est correcte ?_

La proposition est correcte, mais il manque quelques précisions dans la démonstration.

Dans la démonstration du point (1), il faudrait préciser : "il existerait des polynômes P et Q dans K[X] **de degré supérieur à 1**"

Dans celle du point (2), même chose : "alors ils ont un diviseur commun **de degré supérieur à 1**".
Et puis : "ce diviseur commun ne peut être que µ_a lui-même **(ou un polynôme k*µ_a avec k € K\\{0})**"

Voici également une réponse à la question posée en **1.6.2.1** :
_Dans quels cas l’énoncé suivant est vrai : le PGCD de a et b est 1 si et seulement si l’unique diviseur commun de a et b est 1._

Tel quel, l'énoncé n'est (presque) jamais vrai.
Heureusement, il n'y a pas grand chose à changer pour obtenir un énoncé vrai.

Les éléments inversibles sont **toujours** des diviseurs communs à a et b.
En effet, si k est inversible d'inverse k', alors a=k(k'a) donc k|a (même chose pour b).

Or, 1 n'est en général pas l'unique élément inversible d'un anneau A. Par exemple :
- dans Z, il y a deux inversibles : 1 et -1.
- dans K[X], les inversibles sont tous les polynômes constants non nuls.

L'énoncé qui suit est vrai :
1 est **un** PGCD de a et b si et seulement si les seuls diviseurs communs à a et b sont les inversibles.

On peut bien sûr remplacer "**un**" par "**le**" si on a fixé une convention pour assurer l'unicité du PGCD (par exemple, dans Z on impose que le PGCD soit positif, dans K[X] on impose qu'il soit unitaire).

**Comment by cdrcprds** [comment]
Voici également une réponse à la **question (6)** :
_Soit L une extension algébrique de corps de K et a € L. Est-ce que le polynôme minimal de a dans K[X] est l’unique polynôme irréductible unitaire P € K[X] tel que P(a) = 0 ?
D’ailleurs, est-ce qu’un tel polynôme existe ? est unique ? J’utilise cela dans la proposition 5.96._

Le polynôme minimal tel que défini en 5.52 est bien l'unique polynôme irréductible unitaire tel que P(a) = 0.

En voici une démonstration :

**Tout d'abord, fixons les choses :**

On note I(a) l'idéal {P € K[X] tel que P(a) = 0}.
Le corps L est une extension algébrique de K, a est donc racine d'au moins un polynôme non nul de K[X].
I(a) n'est donc pas réduit à {0}.
D'après 5.37, il existe un unique polynôme unitaire µ € K[X] tel que I(a) = (µ).

Ce polynôme µ est le polynôme minimal de a, tel que défini en 5.52. 
Montrons que µ est l'unique polynôme irréductible unitaire de K[X] annulant a :

**µ est un polynôme irréductible unitaire annulant a :**

µ est unitaire, annule a, et d'après 5.54 il est irréductible.

**µ est le seul polynôme irréductible unitaire annulant a :**

Soit µ_1 un polynôme irréductible unitaire tel que µ_1(a) = 0. Montrons que µ_1 = µ :

µ_1 appartient à l'idéal I(a) qui est engendré par µ.
Donc il existe P € K[X] tel que µ_1 = P * µ.

Or, µ_1 est irréductible, donc P ou µ doit être un polynôme constant (non nul, qui plus est).
Ça ne peut pas être µ, c'est donc P qui est constant : P = k (avec k € K*)

Or, µ_1 et µ sont unitaires, donc nécessairement : k = 1.
On en déduit immédiatement que µ_1 = µ.

**Comment by cdrcprds** [comment]
Après relecture, je me rends compte que je n'ai peut-être pas été très clair dans ma réponse à la question 15 sur la pseudo-réduction.

Dans la réduction en question, les matrices Q^tAQ et Q^tBQ (qui sont effectivement diagonales) font intervenir la *transposée* de Q (et non l'*inverse* de Q).

Ce n'est donc pas une diagonalisation, puisque la matrice A n'est pas semblable à la matrice Q^tAQ (elle l'aurait été si Q était orthogonale).

Dans la démonstration, on peut constater qu'on ne réalise pas une réduction d'**endomorphismes** (donc pas une *véritable* diagonalisation), mais plutôt une réduction de **formes bilinéaires symétriques** (ce qui fait intervenir des transposées, et non des inverses).

C'est à mon avis pour cette raison que l'auteur parle de *pseudo*-réduction.

**Comment by LaurentClaessens** [comment]
Bien vu, la différence entre transposée et inverse. Ça m'avais échappé. J'ajoute le fait que ce soit une réduction de forme bilinéaire au `todo.txt` parce que je suis justement en train de revoir la partie sur les matrices et changement de bases dans laquelle il y a justement une remarque concernant le fait que la formule de changement de base d'une matrice vue comme application linéaire ou comme forme bilinéaire n'est pas la même.
C'est en rapport avec ta réponse sur la transposée : en essayant de la taper, j'ai remarqué qu'il y avait des fautes dans les changement de base.

**Comment by LaurentClaessens** [comment]
Je n'oublie pas ... c'est qu'en relisant la proposition 5.96 mentionnée dans la question (6), j'ai remarqué qu'il manquant de nombreuses choses plus haut. Bref, je suis en train de travailler les corps de décomposition et tout ça. 
Des choses commencent à être poussées dans la branche alpha

**Comment by LaurentClaessens** [comment]
Ok. Il aura fallu le temps, mais je crois que tous les points soulevés ici sont faits.
Je me permet de fermé le fil.
Ne pas hésiter à réouvrir si j'ai oublié quelque chose.

**Comment by cdrcprds** [comment]
Il y a quelques fautes de frappe dans la proposition 5.42 :
*Le polynôme µ_a est premier avec tout polynôme de K[X] non annulateur de q.* 
=> "non annulateur de **a**"
Et dans la démonstration :
*En d’autres termes, soit P soit R_1 est inversible. Si P n’est pas inversible, alors R_1 est inversible ; disons Q = k € K*
=>"**R_1** = k"

Dans la définition 3.3 :
*Soient A un anneau et a, b € A. Nous disons que d est un pgcd de a et b si tout diviseur commun
de a et b divise d.*
Il manque la condition "d divise a et b" dans cette définition.

En dehors de ça, tous les points soulevés ont effectivement été réglés.
Il restera juste à supprimer de la liste des questions (chapitre 0.5) celles qui ont eu leur réponse.

**Comment by LaurentClaessens** [comment]
Oui, je l'ai fermé un peu par erreur.
