### ISSUE TITLE
Définition manquante : espace vectoriel

### ISSUE THREAD

**Issue by cdrcprds** [LaurentClaessens/mazhe#61]
Je ne trouve pas de définition d'un espace vectoriel dans le cours :
L'index n'en parle pas, et le chapitre 4 (Espaces vectoriels) commence à peu près par «Soit E un espace vectoriel».

La première occurrence d'«espace vectoriel» que j'ai trouvée dans le cours est à l'exemple 2.88 du chapitre sur les groupes :
_Si E est un espace vectoriel alors (E,+) est un groupe commutatif. L’inverse de x est -x._
Là encore, pas de définition.

Les principales structures algébriques (groupes, anneaux, corps) sont bien définies (dans le chapitre 1), mais visiblement pas les espaces vectoriels.

**Comment by LaurentClaessens** [comment]
C'est poussé dans la branche alpha.
Au passage : 

- Un exemple de groupe était (E,+) lorsque E est un espace vectoriel. Maintenant que le fait que (E,+) soit un groupe est dans la définition d'un espace vectoriel, cet exemple perd de sa superbe. Cet exemple est supprimé.

**Comment by LaurentClaessens** [comment]
Ah tiens, la situation est pire que prévu. En effet la notion d'espace vectoriel est demandée dans la définition d'une algèbre. Donc :
 * un espace vectoriel est maintenant défini comme module sur un corps commutatif
 * la définition tapée hier soir est maintenant donnée comme "rappel".

**Comment by cdrcprds** [comment]
Petite remarque à propos de la commutativité de + :
Elle est traditionnellement exigée dans la définition d'un espace vectoriel ou d'un module, mais elle est en fait superflue puisqu'elle se déduit des autres propriétés.

En développant (1+1).(x+y) de deux façons différentes, ça donne :
- (1+1).(x+y) = 1.(x+y)+1.(x+y) = x+y+x+y
- (1+1).(x+y) = (1+1).x+(1+1).y = x+x+y+y

En simplifiant à gauche par x et à droite par y, on trouve : y+x=x+y.

C'est également valable pour un anneau unitaire.
Wikipédia en parle brièvement dans des notes en bas de page :
- https://fr.wikipedia.org/wiki/Espace_vectoriel#cite_note-4
- https://fr.wikipedia.org/wiki/Module_sur_un_anneau#cite_note-2
- https://fr.wikipedia.org/wiki/Anneau_unitaire#cite_note-AbelSuperflu-4

Je trouve ça suffisamment intéressant pour être souligné.

**Comment by LaurentClaessens** [comment]
Tenuu compte, merci

**Comment by cdrcprds** [comment]
Il manque la condition "(a+b).x = a.x + b.x" dans la nouvelle définition du module.

**Comment by LaurentClaessens** [comment]
Corrigé, merci.
