### ISSUE TITLE
Question sur les corps de rupture

### ISSUE THREAD

**Issue by cdrcprds** [LaurentClaessens/mazhe#62]
_Pourquoi ne définit-on jamais le corps de rupture d’un polynôme à coefficients dans un anneau ? Si A est un anneau, on peut définir un corps de rupture de P€K[X] comme étant un corps contenant A comme sous-anneau dans lequel il existe une racine de P.
D’ailleurs si A est intègre, le corps A[X]/(P) fait l’affaire._

Le problème du _corps de rupture_ d'un polynôme à coefficients dans un anneau, c'est qu'il ne sera en général pas un _corps_.
- Si l'anneau A n'est pas intègre : aucun corps ne pourra contenir A comme sous-anneau.
- Si A est intègre : A[X]/(P) ne fait pas tout à fait l'affaire : l'anneau A[X] ne sera pas principal (à moins que A ne soit justement un corps), et on ne disposera donc pas du théorème de Bézout permettant de trouver un inverse dans A[X]/(P).

On pourrait cependant se contenter de définir la notion d'_anneau de rupture_ (j'aime bien l'idée, personnellement) mais je n'ai rien trouvé à ce sujet sur google.

Néanmoins, si on veut absolument définir un _corps_ de rupture pour un anneau intègre, c'est possible avec Frac(A)[X]/(P) (où Frac(A) est le corps des fractions de A).

**Comment by LaurentClaessens** [comment]
Supposons que A est un anneau intègre, et que P est un polynôme irréductible à coefficients dans A. Si A[X]/(P) est un corps, alors A est un corps ?

**Comment by LaurentClaessens** [comment]
Meileur énoncé : si A est un anneau et si K est un corps contenant A comme sous-anneau (au sens où une partie de K est un anneau isomorphe à A) alors A est principal.
C'est vrai ?

**Comment by cdrcprds** [comment]
> Supposons que A est un anneau intègre, et que P est un polynôme irréductible à coefficients dans A.
Si A[X]/(P) est un corps, alors A est un anneau principal et un corps ?

Je ne sais pas s'il existe ou non des anneaux intègres qui ne soient pas des corps, mais qui "par chance" font que A[X]/(P) soit un corps.
La question mérite d'être étudiée.

> Meileur énoncé : si A est un anneau et si K est un corps contenant A comme sous-anneau (au sens où une partie de K est un anneau isomorphe à A) alors A est principal.
C'est vrai ?

Si un corps contient A comme sous-anneau, on peut seulement en déduire que A est intègre.
On ne peut rien en déduire d'autre : tout anneau intègre A (même ceux qui ne sont pas principaux) admet un corps des fractions (qui contiendra donc A comme sous-anneau).

**Comment by LaurentClaessens** [comment]
Je vais empaqueter tout ça dans une question qui sera placée dans "algèbre->difficile", et on verra si quelqu'un connaît la réponse.

**Comment by cdrcprds** [comment]
> Néanmoins, si on veut absolument définir un _corps_ de rupture pour un anneau intègre, c'est possible avec Frac(A)[X]/(P) (où Frac(A) est le corps des fractions de A).

Je me suis un peu plus penché sur cette question, et il apparaît que c'est un peu plus délicat :
- Si le polynôme P (irréductible sur A) est également irréductible sur Frac(A), on peut effectivement définir le corps de rupture Frac(A)[X]/(P)
- Mais si P _n'est plus_ irréductible lorsqu'on le considère comme un polynôme à coefficients dans Frac(A), ça ne marche plus (je n'avais pas pensé à cette situation...)

Par exemple, le polynôme P=2 à coefficients dans l'anneau intègre Z est bien irréductible (il n'est pas inversible, et n'est pas produit de deux polynômes non inversibles).
Mais dans Q[X], il n'est plus irréductible, puisqu'il y est devenu inversible...
Parler du corps de rupture Q[X]/(2) n'a alors aucun sens.

Pire : dans cet exemple, il n'existe aucun corps (ni même aucun anneau) vérifiant les deux conditions qui nous intéresseraient (contenir une racine de P, et un sous-anneau isomorphe à Z) :
Si le polynôme P=2 a une racine, vu qu'il est de degré 0 (degré strictement inférieur au nombre de racines) c'est le polynôme nul. On a donc affaire à un corps/anneau de caractéristique 2.
Tout sous-anneau sera également de caractéristique 2, et donc certainement pas isomorphe à Z.

Les conditions "A intègre et P irréductible" ne sont donc pas suffisantes :
Si on veut garantir que l'anneau A[X]/(P) contienne un sous-anneau isomorphe à A, il faut encore ajouter la condition : "P non constant" (même si préciser "irréductible et non constant" ressemble à un pléonasme...)

**Comment by LaurentClaessens** [comment]
On aurait donc cet énoncé :
------
Soit un anneau intègre A et un polynôme non constant P dans A[X]. Alors P est irréductible sur Frac(A).
------
Dans ces cas, ça a un sens de parler de corps de décomposition de P en passant par le corps des fractions. La classe des polynômes non constants est assez large.

La question ouverte est de savoir quelle est la classe des anneaux A et des polynômes P tels que nous ayons directement que A[X]/(P) est un corps, sans passer par Frac(A).
En effet, étendre la définition d'un corps de rupture aux anneaux intègres juste en disant qu'on les considère dans le corps des fractions, c'est pas vraiment une extension de la définition.

**Comment by cdrcprds** [comment]
> Soit un anneau intègre A et un polynôme **irréductible** non constant P dans A[X]. Alors P est irréductible sur Frac(A).

Je ne sais pas si cet énoncé est vrai ; par contre, la réciproque est fausse : P=2X²+2 est irréductible sur Q, mais pas sur Z puisque P=2(X²+1)

D'un autre côté, si cet énoncé devait être faux, ce ne serait pas forcément si gênant en pratique :
Si le polynôme P (non constant) n'est plus irréductible sur Frac(A), on peut toujours le décomposer en produit de polynômes irréductibles (puisque Frac(A) est un corps, l'anneau Frac(A)[X} est factoriel).
En prenant un corps de rupture sur l'un des facteurs de la décomposition, ça règle le problème de trouver un corps contenant A dans lequel P a une racine.
