### ISSUE TITLE
lien pdf mazhe mort ?

### ISSUE THREAD

**Issue by Horace89** [LaurentClaessens/mazhe#63]
Bonjour.
Il semblerait que le lien http://laurent.claessens-donadello.eu/pdf/mazhe.pdf soit mort... Existe-t-il un pdf déjà compilé du document ?
Merci pour vos efforts.

**Comment by LaurentClaessens** [comment]
Le 06/02/2018 à 10:58, Horace89 a écrit :
> Bonjour.
> Il semblerait que le lien http://laurent.claessens-donadello.eu/pdf/mazhe.pdf soit mort... Existe-t-il un pdf déjà compilé du document ?
> Merci pour vos efforts.
> 

Bien vu. C'est un maque de rigueur dans le processus de mise en 
production, parce que j'ai oublié de changer de nom en envoyant.

Bref, il est là :
http://laurent.claessens-donadello.eu/pdf/everything.pdf

Je le renvoie avec le bon nom.

Bonne soirée
Laurent
