### ISSUE TITLE
Anglais américain ou anglais britannique ?

### ISSUE THREAD

**Issue by ericguirbal** [LaurentClaessens/mazhe#64]
Dans les chapitres en anglais, on trouve : 
- 2 analyze, 0 analyse
- 2 organize, 0 organise
- 8 particularize, 8 particularise
- 4 realize, 9 realise
- 7 recognize, 0 recognise
- 7 generalize, 7 generalise
- 22 neighborhood, 200 neighbourhood
- etc

Quel dialecte préfères-tu ?

**Comment by LaurentClaessens** [comment]
Sur Wikipédia, il utilisent "neighborhood" et "ize".  Quans je ne suis pas sûr, je fais comme Wikipédia.

**Comment by ericguirbal** [comment]
Va pour l'américain, alors.
