### ISSUE TITLE
Chapitre de Topologie : ordre des éléments à revoir

### ISSUE THREAD

**Issue by bibi6** [LaurentClaessens/mazhe#78]
Bonjour,

Il me semble que le Frido n'a pas défini la notation avant de l'utiliser... mon prochain push le mentionnera en "problèmes et choses à faire".

Mais qui dit définir cela dit définir la notion d'infimum, qui n'a pas été fait non plus par ailleurs il me semble...

**Comment by bibi6** [comment]
En fait c'est plus général:

Dans le chapitre 6, il y a plein de choses à revoir, de telle sorte à mettre les définitions et propositions dans un bon ordre. Là, je tombe sur la notion de point d'accumulation (du fichier 54 ligne 840), qu'on a évoquée avant: fichier 185 ligne 946, et plusieurs fois avant dans le fichier 54.

J'ai vu aussi passer la notion de distance point-ensemble par ailleurs, donc après l'avoir utilisée.

**Comment by LaurentClaessens** [comment]
L'infimum est défini dans la section "maximum, supremum et compagnie", que je suis en train de déplacer vers le chapitre 1, parce que ce sont des notions liées à la structure d'ordre, et non à la structure topologique.

Une grosse difficulté du chapitre "topologie générale" est qu'on a envie de voir R comme cas particulier des espaces métriques, mais les espaces métriques utilisent pas mal de topologie sur R parce qu'au final, la théorie des espaces métriques revient à étudier la fonction "distance", qui est une fonction à valeurs dans R.

Bref, il y a des choix à faire, et ils n'ont pas toujours été faits de façon cohérente.
