### ISSUE TITLE
Référence vers le bas voulue

### ISSUE THREAD

**Issue by bibi6** [LaurentClaessens/mazhe#79]
Bonjour,

Je ne sais pas comment (ni si) les références vers le bas (a priori non autorisées dans le Frido) sont gérées par le code de compilation, mais...

... y a-t-il quelque chose de prévu pour dire "Oui, là j'ai mis une référence sur des trucs qui viennent après, mais c'est juste pour illustrer"?

Parce que je ne vois rien de particulier lorsqu'on définit la notion de limite, qu'on touche mot des dérivées, dans le code (fichier 185 ligne 33 actuellement).

**Comment by LaurentClaessens** [comment]
Ma devise : ne jamais programmer en LaTeX, mais hacker le code LaTeX à la volée en python derrière le dos de TeX.

Dans le cas des références vers le futur, on les obtient en faisant
```
pytex lst_frido.py --verif
```

Il prend un certain temps, mais il fini par sortir une série de :
```
--------- label {DEFooFLGNooCZUkHY ----- 
tex/frido/46_groupes.tex : 85 
    Soit \( G\) le groupe des rotations d'angle\footnote{Voir la définition \ref{DEFooFLGNooCZUkHY}.} \( k\pi/5\) (avec \( k \) entier). Ce groupe est constitué des \og{} dixièmes de tour \fg{}, puisque \( \frac{k\pi} 5 = \frac{2k\pi}{10}.\)
 
tex/frido/190_trigono.tex : 1133 
\begin{definition}      \label{DEFooFLGNooCZUkHY}
 
hash : 0568e62c5894babc23e2ffd9df531d3c6e2a9c12
```

Le premier extrait donne la ligne contenant le \ref fautif, et le second la ligne contenant le \label correspondant.

En dernier se trouve le hash de la ligne fautive. C'est lui qui nous intéresse. Il faut l'ajouter au fichier `commons.py`.

Remarque: si il y a une référence "acceptable" et une non-acceptable sur la même ligne, il vaut mieux couper la ligne en deux.
