### ISSUE TITLE
Puissance

### ISSUE THREAD

**Issue by jube** [LaurentClaessens/mazhe#91]
Concernant la fonction puissance, il est dit dans le chapitre 13.7 : «Pour l'instant, nous savons déjà définir x^n lorsque x \in R et n \in N». Sauf que je n'ai pas trouvé cette définition. J'ai cherché dans le chapitre 1 où je m'attendais à la trouver (pas loin de la définition des anneaux, où la notion de multiplication apparaît pour la première fois) mais elle ne s'y trouve pas.

**Comment by LaurentClaessens** [comment]
Ah oui, bien vu.
Je viens de rajouter.
